### ISSUE TITLE
do_granger_causality getting stuck at computing GPDC connectivity

### ISSUE THREAD

**Issue by ckiefer0** [jdammers/jumeg#158]
When I run the do_granger_causality.py, the function scs.surrogate_connectivity() keeps getting stuck and never returns.
Furthermore I get the following message before surrogate_connectivity is called:

"('\nShape of label_ts -', (55, 68, 106))
 ('\nRunning for model order - ', 15)
 starting checks and MVAR fitting...
 ERROR: Model order not ideal - check parameters !!
 model_order, whiteness, consistency, stability: 15, True, 0.428499, False"

I use scot version 0.3.dev0

By the way, are you using python 3? All the print statements are in brackets.

EDIT: In case you read it already, forget about the whitening.

**Comment by pravsripad** [comment]
The choice of model order is an issue here, for the sake of providing a quick example I have fixed the model order to be 15 which fails the stability test, hence the error "Model order not ideal..."

But apart from this the example runs for me. 

> By the way, are you using python 3? All the print statements are in brackets.
Just preparing for the future ;)

**Comment by ckiefer0** [comment]
So I just tested using mne v.014 and it is still getting stuck. 
Here is the output:

perform normalization using zscoring...
('\nShape of label_ts -', (55, 68, 106))
('\nRunning for model order - ', 15)
starting checks and MVAR fitting...
ERROR: Model order not ideal - check parameters !!
model_order, whiteness, consistency, stability: 15, True, 0.409459, False

Also when I stop the script using ctrl+c it kinda crashes and does not terminate.

**Comment by ckiefer0** [comment]
Indeed, the problem lies in n_jobs. When I set n_jobs to 1 everything runs through fine.

**Comment by pravsripad** [comment]
Very well, there should be something wrong with the implementation of parallelization. We can keep this open until this issue can be resolved/worked around.

**Comment by pravsripad** [comment]
Found to be a system specific problem.
